name: 'Z-Wave Button Delphimon'
packageKey: 'zwave-button delph'
permissions:
  zwave: {}
description: "SmartThings driver for Z-Wave button and remote devices"
vendorSupportInformation: "https://support.smartthings.com"
